import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'notch',
  description: 'Generated by create next app'
}

export default function RootLayout(props: {
  children: React.ReactNode
  analytics: React.ReactNode
  team: React.ReactNode
  auth: React.ReactNode
}) {
  return (
    <div className="max-w-4xl mx-auto h-[450px] mt-32 grid grid-cols-2 md:grid-cols-3 grid-rows-2 gap-2 justify-center content-center px-2">
      {props.children}
      {props.team}
      {props.analytics}
      {props.auth}
    </div>
  )
}
