import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'notch',
  description: 'Generated by create next app'
}

export default function RootLayout(props: {
  children: React.ReactNode
  analytics: React.ReactNode
  team: React.ReactNode
  auth: React.ReactNode
}) {
  return (
    <div className="grid grid-cols-4 gap-4 h-72 relative">
      {props.children}
      {props.team}
      {props.analytics}
      {props.auth}
    </div>
  )
}
